config/routes.rb
AutocompleteProjectCollaborators::Application.routes.draw do

  root :to => 'projects#index'

  resources :projects do
    get :autocomplete_user_name, :on => :collection
  end

  post 'projects/:id/add_collaborator' => 'projects#add_collaborator', :as => 'add_collaborator'
  post 'projects/:id/delete_collaborator' => 'projects#delete_collaborator', :as => 'delete_collaborator'

  get 'users/index' => 'users#index', :as => 'users'

end

app/models/collaborating.rb
class Collaborating < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

app/models/collaboratings.rb
class Collaboratings < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :collaboratings, :dependent => :destroy
  has_many :collaborators, :through => :collaboratings, :source => :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :collaboratings, :dependent => :destroy
  has_many :collaborated_projects, :through => :collaboratings, :source => :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, :only => [:show, :add_collaborator, :delete_collaborator]
  autocomplete :user, :name

  def index
    @projects = Project.all
  end

  def show
    @collaborators = @project.collaborators
  end

  def add_collaborator
    @collaborator = User.find_by_name(params[:collab])
    return false if @collaborator.blank?
    if @project.collaborators.include?(@collaborator)
      @token = true
      return
    end
    @project.collaborators << @collaborator
    respond_to do |format|
      format.js
    end
  end

  def delete_collaborator
    @collaborator = User.find_by_name(params[:collab])
    @project.collaborators.delete(@collaborator)
    respond_to do |format|
      format.js
    end
  end

  private
  def find_project
    @project = Project.find_by_id(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AutocompleteProjectCollaborators</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= yield :template_js %>
</body>
</html>

app/views/projects/_collaborator.html.erb
<li class="uid-<%= user.id %>">
  <span><%= user.name %></span>
  <%= link_to 'Delete', delete_collaborator_path(:collab => user.name), :method => :post,
  :remote => true, :class => "btn btn-danger right" %>
</li>

app/views/projects/add_collaborator.js.erb
<% if @collaborator.present? %>
  <% if @token %>
    $('.collab-error').html("User <%= @collaborator.name %> is already a collaborator!")
    $('.collab-error').css("display", "block");
  <% else %>
    $('.collabs').append("<%= j render 'collaborator', :user => @collaborator %>")
  <% end %>
<% end %>

app/views/projects/delete_collaborator.js.erb
$("li.uid-<%= @collaborator.id %>").remove();

app/views/projects/index.html.erb
<div class="container">
  <div class="nav">
    <span>Listing Projects</span>
    <%= link_to "Users", users_path %>
  </div>
  <ul class="wrapper">
    <% @projects.each do |project| %>
    <li>
      <% if project.name == "haoqicat" %>
        <%= image_tag "haoqicat.png" %>
      <% else %>
        <%= image_tag "happycasts.png" %>
      <% end %>
      <%= project.name %>
      <%= link_to 'Add collaborators', project, :class => "btn btn-success right" %>
    </li>
    <% end %>
  </ul>
</div>

app/views/projects/show.html.erb
<div class="container">
  <div class="nav">
    <span>Collaborators</span>
    <%= link_to 'Home', root_path %>
  </div>

  <ul class="collabs wrapper">
    <% if @collaborators.present? %>
      <% @collaborators.each do |user| %>
        <li class="uid-<%= user.id %>">
          <span><%= user.name %></span>
          <%= link_to 'Delete', delete_collaborator_path(:collab => user.name), :method => :post,
          :remote => true, :class => "btn btn-danger right" %>
        </li>
      <% end %>
    <% end %>
  </ul>

  <%= form_tag add_collaborator_path, :method => :post, :remote => true do %>
    <%= autocomplete_field_tag :collab, '', autocomplete_user_name_projects_path, :size => 25 %>
    <%= button_tag 'Add collaborator', :disabled => true, :class => 'btn btn-success btn-collab' %>
  <% end %>

  <div class="collab-error"></div>

  <% content_for :template_js do %>
    <script>
      $('#collab').bind('input', function() {
        $('.btn-collab').attr("disabled", true);
      });
      $('#collab').bind('railsAutocomplete.select', function(){
        $('.btn-collab').attr("disabled", false);
      });
    </script>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="nav">
    <span>Listing Users</span>
    <%= link_to "Home", root_path %>
  </div>
  <ul>
    <% @users.each do |user| %>
      <li>
        <%= user.name %>
      </li>
    <% end %>
  </ul>
</div>